name: multiplesteps
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: multisteps
        run: |
          echo "first multi command job"
          echo "sencond multi command job"
